ruby/strscan

Rakefile
benchmark/scan.yaml
ext/strscan/strscan.c
strscan.gemspec
test/strscan/test_stringscanner.rb

It's only for head only match case such as StringScanner#scan.
If we use a String as a pattern, we can improve match performance.
Here is a result of the including benchmark. It shows String as a
pattern is 1.25x faster than Regexp as a pattern.
% rake benchmark
/tmp/local/bin/ruby -S benchmark-driver benchmark/scan.yaml
Warming up --------------------------------------
regexp    12.094M i/s -     12.242M times in 1.012250s (82.69ns/i, 277clocks/i)
string    14.653M i/s -     14.889M times in 1.016124s (68.25ns/i, 252clocks/i)
Calculating -------------------------------------
regexp    14.713M i/s -     36.281M times in 2.465970s (67.97ns/i, 254clocks/i)
string    18.422M i/s -     43.959M times in 2.386255s (54.28ns/i, 201clocks/i)
Comparison:
string:  18421631.8 i/s
regexp:  14712660.7 …

Accept String as a pattern

---

ext/strscan/strscan.c
test/strscan/test_stringscanner.rb

Six years ago, [the Rouge library](https://github.com/rouge-ruby/rouge) author, @jneen, reported that there was [a bug in the handling of anchors](http://bugs.ruby-lang.org/issues/7092) in StringScanner. At the time, StringScanner did not have a maintainer and the view was expressed that this behaviour was intended.
In short, the bug is that anchors in regular expressions don't work properly in StringScanner. This can be seen in the sample code below (taken from the original bug report):
```ruby
require 'strscan'
ss = StringScanner.new("ab")
ss.scan(/./)
#=> "a"
ss.scan(/^./) # expecting nil, since the head is in the middle of a line
#=> "b"
```
The cause of the bug is the way `strscan_do_scan()` is implemented in `ext/strscan/strscan.c`. This function calls out to `onig_match()` and …

Fix anchors

---

test/strscan/test_stringscanner.rb

Based on the discussion at https://github.com/ruby/strscan/pull/6#issuecomment-515832179, this tests that the behavior of `^` correctly fails to match when the stream is not at the beginning of a line.

Add a test for when ^ should fail to match

---

ext/strscan/strscan.c
test/strscan/test_stringscanner.rb

Ruby 2.7 deprecates taint and it no longer has an effect.
The lack of taint support should not cause a problem in
previous Ruby versions.

Remove taint support

---

ext/strscan/strscan.c

`$KCODE` has been deprecated and not effective since years ago.

Replaced examples using $KCODE with encodings

---

ext/strscan/strscan.c

iff means if and only if, but readers without that knowledge might
assume this to be a spelling mistake. To me, this seems like
exclusionary language that is unnecessary. Simply using "if and only if"
instead should suffice.
strscan changes from https://github.com/ruby/ruby/pull/4035

Replace "iff" with "if and only if"

---

ext/strscan/strscan.c
test/strscan/test_stringscanner.rb

ref: https://bugs.ruby-lang.org/issues/17756
This code makes segmentation fault.
```console
$ ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
```
```ruby
require 'strscan'
string = 'ruby'
scanner = StringScanner.new(string)
pre = Module.new do
def byteslice(*args)
end
end
string.singleton_class.prepend(pre)
scanner.charpos
```
The crash report.
```text
Process:               ruby [95519]
Path:                  /Users/USER/*/ruby
Identifier:            ruby
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        zsh [92870]
Responsible:           iTerm2 [775]
User ID:               501
Date/Time:             2021-03-28 03:12:19.319 +0900
OS Version:            macOS 11.2.3 (20D91)
Report Version:        12
Bridge OS Version:     5.2 …
```

Fix segmentation fault of `StringScanner#charpos` when `String#byteslice` returns non string value [Bug #17756]

---

ext/strscan/strscan.c

Replace characters with \u escapes.
No other C source files shipped with ruby include non-US-ASCII
characters.

Remove non-US-ASCII characters from C source code

---

README.md

I wanted to follow the link in the build status badge, to see the reasons for it being red, but the link was only to the SVG, haha.
This PR changes the link to point to the workflow results page.

Fix link to CI workflows in the status badge

---

.github/workflows/ci.yml
.gitignore
Gemfile
Rakefile
ext/java/org/jruby/ext/strscan/RubyStringScanner.java
ext/java/org/jruby/ext/strscan/StringScannerLibrary.java
lib/strscan.rb
strscan.gemspec

Finally getting around to addressing #15. Initial import has gone well but there are a few failures to look into, probably just feature/fix drift in our implementation.
I will fix the issues and make sure this packages properly as a gem, so we can start using it in JRuby 9.4 (equivalent to CRuby 3.0).
TODO:

Import JRuby's strscan

---

.github/workflows/ci.yml
Rakefile
ext/strscan/extconf.rb
lib/jruby/strscan.rb
lib/strscan.rb
run-test.rb
strscan.gemspec
test/strscan/test_ractor.rb
test/strscan/test_stringscanner.rb

* This is necessary since lib/strscan.rb was added (https://github.com/ruby/strscan/pull/25), as the
TruffleRuby stdlib strscan.rb is no longer found first by `require "strscan"`.
* Write conditions in a way that any other Ruby implementation would
simply use its stdlib until it is added explicit support in this gem.
Fixes https://github.com/oracle/truffleruby/issues/2420

Add support for TruffleRuby in the gem

---

strscan.gemspec

From https://github.com/ruby/strscan/pull/25#discussion_r862348343

Simplify condition in strscan.gemspec

---

strscan.gemspec

why?
```
1. Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.
```
AFAIK, a gem is a redistribution of source code and/or binary formats, so it should include the license. Also makes it easier for users of the gem to compile a list of all licenses they use.

Include license in gem

---

.github/dependabot.yml

This only makes PRs with updates to the GitHub Actions versions. (Not gems, not any other packages.)

Add dependabot to update GH actions

---

ext/strscan/strscan.c
strscan.gemspec
test/strscan/test_stringscanner.rb

fix: support named captures

---

ext/strscan/strscan.c

The doc of `rest?` was unclear about return value. This commit adds the return value to the doc.

Mention return value of `rest?` in the doc

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java

JOni 2.2 will hide these public fields and the direct constructors for Region, so these adapters will bridge the gap until the new API is widely available. The adapter and calls to it can be removed once JRuby has shipped a few releases of 9.4 (and possibly 9.3) with the updated JOni.

Introduce an adapter from joni 2.1 to 2.2

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java

This support was never finished, causing several tests in TestStringScannerFixedAnchor to fail. However, because of #56 I did not realize these were still failing.
@kou This can be merged and released any time, and I have confirmed in the JRuby repository that it does indeed allow all remaining `fixed_anchor` tests to pass. I have no explanation for #56 right now.

Finish fixed_anchor support in the JRuby ext

---

test/strscan/test_stringscanner.rb

`string` returns the original string after `scan` is called. Current test doesn't check this behavior and now it's covered.

Add test case to `test_string`

---

test/strscan/test_stringscanner.rb

test: Run test more with fixed anchor mode

---

.gitignore

I always ignore `lib/strscan.bundle` manually.

Add .bundle to gitignore

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java
ext/strscan/strscan.c
test/strscan/test_stringscanner.rb

```ruby
StringScanner.new('foo').named_captures
```
This commit fixes a crash in the case above.

Fix a crash when `named_captures` called on new instance

---

ext/strscan/extconf.rb
ext/strscan/strscan.c

rb_reg_onig_match performs preparation, error handling, and cleanup for matching a regex against a string. This reduces repetitive code and removes the need for StringScanner to access internal data of regex.
This commit syncs strscan to commit ruby/ruby@7193b404a1a56e50f8046d0382914907020c1559.

Use new function rb_reg_onig_match

---

.github/workflows/ci.yml
ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java

A few minor tweaks.
* Cache field accesss throughout
* Arity-split `values_at` method for low arity calls
* General cleanup

Minor cleanup and optimization

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java
ext/strscan/strscan.c
test/strscan/test_stringscanner.rb

fix https://github.com/ruby/strscan/issues/70
If there is no substring matching the group (s[3]), the behavior is different.
If there is no substring matching the group, the corresponding element (s[3]) should be nil.
```
s = StringScanner.new('foobarbaz') #=> #<StringScanner 0/9 @ "fooba...">
s.scan /(foo)(bar)(BAZ)?/  #=> "foobar"
s[0]           #=> "foobar"
s[1]           #=> "foo"
s[2]           #=> "bar"
s[3]           #=> nil
s.captures #=> ["foo", "bar", ""]
s.captures.compact #=> ["foo", "bar", ""]
```
```
s = StringScanner.new('foobarbaz') #=> #<StringScanner 0/9 @ "fooba...">
s.scan /(foo)(bar)(BAZ)?/  #=> "foobar"
s[0]           #=> "foobar"
s[1]           #=> "foo"
s[2]           #=> "bar"
s[3]           #=> nil
s.captures #=> ["foo", "bar", nil]
s.captures.compact #=> ["foo", …
```

StringScanner#captures: Return nil not "" for unmached capture

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java

The empty string here should match the encoding of the scanner string.
Fixes #78

Use str encoding for empty rest string

---

.github/workflows/ci.yml
ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java

This PR removes the code path for OldRegionAdapter, now that all published JRuby versions are using "new API" for `Region`, so no adapting is necessary.
headius mentioned in an off-GitHub conversation:
> Yeah we had a transition period where it supported both old and new
but now all released JRuby should be on the new version
> (Using Region) should be fine, especially since 9.3 can't really install the gem (it will be ignored unless explicitly activated) and 9.4 has had the new region logic for several releases

JRuby extension: drop old-Joni-version support

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java

* RubyArray is generic and should be declared with <?> at minimum.
* The serialization changes are due to the RubyObject hierarchy implementing Serializable. Unfortunately the Joni classes are not themselves serializable, so these changes are solely to suppress the warnings.

Clean up source-level warnings on Java 21

---

test/strscan/test_stringscanner.rb

Add test to check encoding for empty string
See: https://github.com/ruby/strscan/issues/78#issuecomment-1890849891

Add test to check encoding for empty string

---

.github/workflows/ci.yml

fix ruby/strscan#73
I took some inspiration from https://github.com/ruby/uri/blob/master/.github/workflows/test.yml and then I edited the necessary values.
(I put this as a Draft PR, since I am not sure about all the details, which engines and versions will be included.)

CI: Use shared versions GH Actions workflow

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java

Do not make shared strings for extracted ranges

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java
test/strscan/test_stringscanner.rb

Don't add begin to length for new string slice

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java
ext/strscan/strscan.c
run-test.rb
test/strscan/test_stringscanner.rb

This commit adds `scan_byte` and `peek_byte`. `scan_byte` will scan the current byte, return it as an integer, and advance the cursor. `peek_byte` will return the current byte as an integer without advancing the cursor.
Currently `StringScanner#get_byte` returns a string, but I want to get the current byte without allocating a string. I think this will help with writing high performance lexers.
Thanks!

Add a method for peeking and scanning bytes as integers

---

test/strscan/test_stringscanner.rb

The methods were added in #89 but they aren't implemented in TruffleRuby yet. So let's skip them for now to have CI green.

Omit tests for `#scan_byte` and `#peek_byte` on TruffleRuby temporary

---

Rakefile
ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java

The Java version is hardcoded like the C version, but has not been getting updated. This will at least let it be updated by the rake target version:bump, but any manual version number changes still have to be done to both the C code and the Java code.
Fixes #97
Note this also corrects the version to the last release, so when it is bumped again it should update.

Update Java ext version and add script logic for bump

---

.github/workflows/ci.yml

As of test-unit-ruby-core 1.0.5, test-unit is not in the dependency list.

Run test with installed gems

---

benchmark/check_until.yaml
ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java
ext/strscan/strscan.c
test/strscan/test_stringscanner.rb

It supports non-head match cases such as StringScanner#scan_until.
If we use a String as a pattern, we can improve match performance.
Here is a result of the including benchmark. 
It shows String as a pattern is 1.18x faster than Regexp as a pattern.
```
$ benchmark-driver benchmark/check_until.yaml
Warming up --------------------------------------
regexp     9.403M i/s -      9.548M times in 1.015459s (106.35ns/i)
regexp_var     9.162M i/s -      9.248M times in 1.009479s (109.15ns/i)
string     8.966M i/s -      9.274M times in 1.034343s (111.54ns/i)
string_var    11.051M i/s -     11.190M times in 1.012538s (90.49ns/i)
Calculating -------------------------------------
regexp    10.319M i/s -     28.209M times in 2.733707s (96.91ns/i)
regexp_var    10.032M i/s -     27.485M times in …
```

Accept String as a pattern at non head

---

ext/strscan/strscan.c

- before: #106
In `rb_strseq_index()`, the result of `rb_enc_check()` is used.
- https://github.com/ruby/ruby/blob/6c7209cd3788ceec01e504d99057f9d3b396be84/string.c#L4335-L4368
> enc = rb_enc_check(str, sub);
> return strseq_core(str_ptr, str_ptr_end, str_len, sub_ptr, sub_len, offset, enc);
- https://github.com/ruby/ruby/blob/6c7209cd3788ceec01e504d99057f9d3b396be84/string.c#L4309-L4318
```C
strseq_core(const char *str_ptr, const char *str_ptr_end, long str_len,
const char *sub_ptr, long sub_len, long offset, rb_encoding *enc)
{
const char *search_start = str_ptr;
long pos, search_len = str_len - offset;
for (;;) {
const char *t;
pos = rb_memsearch(sub_ptr, sub_len, search_start, search_len, enc);
```
It shows String as a pattern is 1.24x faster than Regexp as a pattern.
```
$ …
```

[CRuby] Optimize `strscan_do_scan()`: Remove unnecessary use of `rb_enc_get()`

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java

- before: #106
Because they are identical.
https://github.com/ruby/strscan/blob/d31274f41b7c1e28f23d58cf7bfea03baa818cb7/ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java#L267-L268
https://github.com/ruby/strscan/blob/d31274f41b7c1e28f23d58cf7bfea03baa818cb7/ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java#L359-L361
It shows String as a pattern is 2.33x faster than Regexp as a pattern.
```
$ benchmark-driver benchmark/check_until.yaml
Warming up --------------------------------------
regexp     7.421M i/s -      7.378M times in 0.994235s (134.75ns/i)
regexp_var     7.302M i/s -      7.307M times in 1.000706s (136.95ns/i)
string    12.715M i/s -     12.707M times in 0.999388s (78.65ns/i)
string_var    13.575M i/s -     13.533M times in 0.996914s (73.66ns/i)
Calculating …
```

[JRuby] Optimize `scan()`: Use `strBL.getBegin() + curr` instead of `currPtr()`

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java
test/strscan/test_stringscanner.rb

- before: #109
https://github.com/ruby/strscan/blob/d31274f41b7c1e28f23d58cf7bfea03baa818cb7/ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java#L371-L373
This means the following :
`if (str.size() - curr < pattern.size()) return context.nil;`
A similar check is made within `StringSupport#index()` within `!headonly`.
https://github.com/jruby/jruby/blob/be7815ec02356a58891c8727bb448f0c6a826d96/core/src/main/java/org/jruby/util/StringSupport.java#L1706-L1720
```Java
public static int index(ByteList source, ByteList other, int offset, Encoding enc) {
int sourceLen = source.realSize();
int sourceBegin = source.begin();
int otherLen = other.realSize();
if (otherLen == 0) return offset;
if (sourceLen - offset < otherLen) return -1;
```
- source = `strBL`
- other = `patternBL`
- offset = …

[JRuby] Optimize `scan()`: Remove duplicate `if (restLen() < patternsize()) return context.nil;` checks in `!headonly`.

---

doc/strscan/strscan.md

See current doc, search for '## Target Substring', notice the backtick that isn't visible to the GitHub md parser.
https://github.com/ruby/strscan/blob/843e931d134b0a8f0284296250454374e3f8a6aa/doc/strscan/strscan.md
Fixed in the PR, see:
https://github.com/MSP-Greg/strscan/blob/00-strscan.md/doc/strscan/strscan.md

[DOC] doc/strscan/strscan.md - fix triple backtick

---

benchmark/scan.yaml
benchmark/search.yaml

To improve the parsing process, I would like to add benchmarks for all parsing processes.
- scan_full(regexp, false, true) == StringScanner#check
- scan_full(regexp, false, false) ==  StringScanner#match?
```
$ benchmark-driver benchmark/scan.yaml
Warming up --------------------------------------
check(reg)    10.558M i/s -     10.848M times in 1.027445s (94.71ns/i)
check(str)    13.368M i/s -     13.782M times in 1.030978s (74.80ns/i)
match?(reg)    16.080M i/s -     16.247M times in 1.010340s (62.19ns/i)
match?(str)    23.336M i/s -     23.501M times in 1.007088s (42.85ns/i)
Calculating -------------------------------------
check(reg)    11.601M i/s -     31.675M times in 2.730287s (86.20ns/i)
check(str)    15.217M i/s -     40.104M times in 2.635475s (65.72ns/i)
match?(reg)    18.781M …
```

Add scan and search benchmark

---

ext/jruby/lib/strscan.rb
ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java
ext/strscan/strscan.c
lib/strscan/strscan.rb
strscan.gemspec
test/strscan/test_stringscanner.rb

Followup: https://github.com/ruby/strscan/pull/115
`scan_integer` is now implemented in Ruby as to efficiently handle keyword arguments without allocating a Hash. Given the goal of `scan_integer` is to more effciently parse integers without having to allocate an intermediary object, using `rb_scan_args` would defeat the purpose.
Additionally, the C implementation now uses `rb_isdigit` and `rb_isxdigit`, because on Windows `isdigit` is locale dependent.
cc @kou

StringScanner#scan_integer support base 16 integers

---

ext/strscan/strscan.c

Profiling shows a lot of time spent in various encoding check functions. I'm working on optimizing them on the Ruby side, but if we assume most strings are one of the simple 3 encodings, we can skip a lot of overhead.
```ruby
require 'strscan'
require 'benchmark/ips'
source = 10_000.times.map { rand(9999999).to_s }.join(",").force_encoding(Encoding::UTF_8).freeze
def scan_to_i(source)
scanner = StringScanner.new(source)
while number = scanner.scan(/\d+/)
number.to_i
scanner.skip(",")
end
end
def scan_integer(source)
scanner = StringScanner.new(source)
while scanner.scan_integer
scanner.skip(",")
end
end
Benchmark.ips do |x|
x.report("scan.to_i") { scan_to_i(source) }
x.report("scan_integer") { scan_integer(source) }
x.compare!
end
```
Before:
```
ruby 3.3.4 (2024-07-09 revision …
```

Micro optimize encoding checks

---

test/strscan/test_stringscanner.rb

https://rubyci.s3.amazonaws.com/debian11/ruby-master/log/20241128T153002Z.log.html.gz
```
/home/chkbuild/chkbuild/tmp/build/20241128T153002Z/ruby/test/strscan/test_stringscanner.rb:908: warning: ambiguous first argument; put parentheses or a space even after `-` operator
```

Prevent a warning "ambiguous first argument" during a test

---

doc/strscan/strscan.md

Added support for string pattern type in https://github.com/ruby/strscan/pull/106.
And fix Success Return content.

[DOC] doc/strscan/strscan.md - update Matcher Methods

---

README.md
doc/strscan/helper_methods.md
doc/strscan/methods/get_byte.md
doc/strscan/methods/get_charpos.md
doc/strscan/methods/get_pos.md
doc/strscan/methods/getch.md
doc/strscan/methods/scan.md
doc/strscan/methods/scan_until.md
doc/strscan/methods/set_pos.md
doc/strscan/methods/skip.md
doc/strscan/methods/skip_until.md
doc/strscan/methods/terminate.md
doc/strscan/strscan.md
ext/strscan/strscan.c

Split off from https://github.com/ruby/ruby/pull/12322

[DOC] Add syntax highlighting to MarkDown code blocks

---

.github/workflows/ci.yml
ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java

This is a re-port of the C code from @byroot for fast base 10 and base 16 integer scanning.
In https://github.com/ruby/strscan/issues/125, @kou pointed out there's an intermittent failure in the JRuby extension. We were unable to confirm exactly the circumstances that cause that failure, but this re-port should at least help reduce the change it is a bug in the original Java code.

Re-port new integer-scanning utility methods

---

doc/strscan/strscan.md

[DOC] Fix typo in documentation

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java
ext/strscan/strscan.c
test/strscan/test_stringscanner.rb

Update registers after parsing integers

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java
ext/strscan/strscan.c
test/strscan/test_stringscanner.rb

Fix a bug that scan_until behaves differently with Regexp and String patterns

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java
ext/strscan/strscan.c
test/strscan/test_stringscanner.rb

Fix a bug that scanning methods that don't use Regexp don't clear named capture groups

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java
ext/strscan/strscan.c
test/strscan/test_stringscanner.rb

Fix a bug that inconsistency of IndexError vs nil for unknown capture group

---

.github/workflows/ci.yml
test/strscan/test_stringscanner.rb

Changes:
- enabled tests passing on TruffleRuby
- removed `truffleruby` and keep only `truffleruby-head` in CI

Enable tests passing on TruffleRuby

---

ext/strscan/strscan.c

For a reason unknown, even though `pos` is stored as a `long`, the `#pos` and `#pos=` treat it as an `int`, which prevent seeking into strings larger than 2GiB.
cc @kou

Allow parsing strings larger than 2GiB

---

.github/workflows/ci.yml

The setup-ruby logic for JRuby on Windows must not be fully choosing Java 21, so when it tries to compile the extension it's still using an older version. This fixes it.

Fix JRuby CI for Windows

---

ext/jruby/org/jruby/ext/strscan/RubyStringScanner.java
test/strscan/test_stringscanner.rb

Fix GH-152
CRuby can walk off the end because there's always a null byte. In JRuby, the byte array is often (usually?) the exact size of the string. So we need to check if len++ walked off the end.
This code was ported from a version by @byroot in https://github.com/ruby/strscan/pull/127 but I missed adding this check due to a lack of tests. A test is included for both "-" and "+" parsing.

jruby: Check if len++ walked off the end

---

ext/strscan/strscan.c

StringScanner holds the string being scanned, and a regex for methods
like `match?`. Triggering the write barrier for those allows us to mark
this as WB protected.

Implement Write Barrier
